import { MenuItem } from './types';

export const menuItems: MenuItem[] = [
  {
    id: 'dashboard',
    label: 'Dashboard',
    icon: '📊',
    path: '/',
    permission: [1, 2], // Admin e Operador
  },
  {
    id: 'operacional',
    label: 'OPERACIONAL',
    icon: '⚡',
    path: '#',
    permission: [1, 2],
    children: [
      {
        id: 'pdv',
        label: 'PDV - Ponto de Venda',
        icon: '🛒',
        path: '/vendas/pdv',
        permission: [1, 2],
      },
      {
        id: 'caixa',
        label: 'Caixa',
        icon: '💰',
        path: '/caixa',
        permission: [1, 2],
      },
      {
        id: 'historico-vendas',
        label: 'Histórico de Vendas',
        icon: '📋',
        path: '/vendas/historico',
        permission: [1, 2],
      },
    ],
  },
  {
    id: 'alunos',
    label: 'ALUNOS',
    icon: '👨‍🎓',
    path: '#',
    permission: [1, 2],
    children: [
      {
        id: 'contas-alunos',
        label: 'Contas dos Alunos',
        icon: '💳',
        path: '/alunos/contas',
        permission: [1, 2],
      },
      {
        id: 'historico-aluno',
        label: 'Histórico de Consumo',
        icon: '📊',
        path: '/alunos/historico',
        permission: [1, 2],
      },
      {
        id: 'pacotes',
        label: 'Pacotes de Alimentação',
        icon: '🍱',
        path: '/alunos/pacotes',
        permission: [1, 2],
      },
      {
        id: 'restricoes',
        label: 'Restrições Alimentares',
        icon: '🍽️',
        path: '/alunos/restricoes',
        permission: [1, 2],
      },
      {
        id: 'observacoes',
        label: 'Observações',
        icon: '📝',
        path: '/alunos/observacoes',
        permission: [1, 2],
      },
      {
        id: 'importar-saldos',
        label: 'Importar Saldos',
        icon: '📥',
        path: '/alunos/importar-saldos',
        permission: [1], // Apenas Admin
      },
    ],
  },
  {
    id: 'produtos-estoque',
    label: 'PRODUTOS & ESTOQUE',
    icon: '📦',
    path: '#',
    permission: [1, 2],
    children: [
      {
        id: 'cadastro-produtos',
        label: 'Cadastro de Produtos',
        icon: '🏷️',
        path: '/produtos',
        permission: [1, 2],
      },
      {
        id: 'tipos-produtos',
        label: 'Tipos de Produtos',
        icon: '📦',
        path: '/produtos/tipos',
        permission: [1, 2],
      },
      {
        id: 'controle-estoque',
        label: 'Controle de Estoque',
        icon: '📦',
        path: '/estoque',
        permission: [1, 2],
      },
      {
        id: 'movimentacoes',
        label: 'Movimentações',
        icon: '📦',
        path: '/estoque/movimentacoes',
        permission: [1, 2],
      },
    ],
  },
  {
    id: 'funcionarios-escola',
    label: 'FUNCIONÁRIOS ESCOLA',
    icon: '👨‍🏫',
    path: '#',
    permission: [1, 2],
    children: [
      {
        id: 'contas-funcionarios-escola',
        label: 'Contas de Funcionários',
        icon: '💼',
        path: '/financeiro/funcionarios/contas',
        permission: [1, 2],
      },
      {
        id: 'faturas',
        label: 'Faturas',
        icon: '📄',
        path: '/financeiro/faturas',
        permission: [1, 2],
      },
      {
        id: 'precos-cargo',
        label: 'Preços por Cargo',
        icon: '💰',
        path: '/financeiro/funcionarios/precos',
        permission: [1],
      },
    ],
  },
  {
    id: 'relatorios',
    label: 'RELATÓRIOS',
    icon: '📑',
    path: '#',
    permission: [1, 2],
    children: [
      {
        id: 'relatorio-vendas',
        label: 'Relatório de Vendas',
        icon: '💰',
        path: '/relatorios/vendas',
        permission: [1, 2],
      },
      {
        id: 'relatorio-consumo',
        label: 'Relatório de Consumo',
        icon: '📊',
        path: '/relatorios/consumo',
        permission: [1, 2],
      },
      {
        id: 'relatorio-estoque',
        label: 'Relatório de Estoque',
        icon: '📦',
        path: '/relatorios/estoque',
        permission: [1, 2],
      },
      {
        id: 'relatorio-faturas-pdf',
        label: 'Relatório de Faturas',
        icon: '📄',
        path: '/financeiro/relatorios/faturas',
        permission: [1],
      },
    ],
  },
  {
    id: 'financeiro',
    label: 'FINANCEIRO',
    icon: '💰',
    path: '#',
    permission: [1], // Apenas Admin
    children: [
      {
        id: 'dashboard-financeiro',
        label: 'Dashboard Financeiro',
        icon: '📊',
        path: '/financeiro/dashboard',
        permission: [1],
      },
      {
        id: 'fornecedores',
        label: 'Fornecedores',
        icon: '🏢',
        path: '/financeiro/fornecedores',
        permission: [1],
      },
      {
        id: 'contas-pagar',
        label: 'Contas a Pagar',
        icon: '📄',
        path: '/financeiro/contas-pagar',
        permission: [1],
      },
      {
        id: 'contas-receber',
        label: 'Contas a Receber',
        icon: '📥',
        path: '/financeiro/contas-receber',
        permission: [1],
      },
      {
        id: 'relatorios-financeiros',
        label: 'Relatórios Financeiros',
        icon: '📈',
        path: '/financeiro/relatorios',
        permission: [1],
      },
    ],
  },
  {
    id: 'administracao',
    label: 'ADMINISTRAÇÃO',
    icon: '⚙️',
    path: '#',
    permission: [1], // Apenas Admin
    children: [
      {
        id: 'funcionarios-cantina',
        label: 'Funcionários da Cantina',
        icon: '👨‍🍳',
        path: '/funcionarios-cantina',
        permission: [1],
      },
      {
        id: 'usuarios-sistema',
        label: 'Usuários do Sistema',
        icon: '👥',
        path: '/configuracoes/usuarios',
        permission: [1],
      },
      {
        id: 'perfis-acesso',
        label: 'Perfis de Acesso',
        icon: '🔐',
        path: '/configuracoes/perfis',
        permission: [1],
      },
      {
        id: 'parametros',
        label: 'Parâmetros do Sistema',
        icon: '🔧',
        path: '/configuracoes/parametros',
        permission: [1],
      },
    ],
  },
];
